#!/usr/bin/env bash
sleep 1
echo "Killing xdg-desktop-portal-hyprland and xdg-desktop-portal"
killall -e xdg-desktop-portal-hyprland
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &